version: 2

updates:
  - package-ecosystem: "gomod"
    directory: "/"
    target-branch: "nightly"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Phoenix"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "go"

  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "nightly"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:15"
      timezone: "America/Phoenix"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "nightly"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:30"
      timezone: "America/Phoenix"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
